### ISSUE TITLE
TypeError: Cannot read property 'members' of undefined

### ISSUE THREAD

**Issue by s4turns** [s4turns/PackBot#16]
https://github.com/s4turns/PackBot/blob/f2761a7b2d176ce51f7216fa8500b7c536c9a5c8/commands/bong.js#L4

23:25:20 <@interdom3> let roleMembers = message.guild.roles.get(role).members.map(m=>m.user.tag);
23:25:21 <@interdom3> TypeError: Cannot read property 'members' of undefined
23:25:22 <@interdom3> pls

**Comment by s4turns** [comment]
This issue in on another discord server the bot was invited to.

**Comment by xDDFF** [comment]
Fixed, this happened because role was hardcoded on the *.js
// let role = "323541436765306880";

Since this role was hardcoded when the *.js was used in a different server, ti would break.

fixed: commented out the role and roleMembers

**Comment by s4turns** [comment]
👍
