### ISSUE TITLE
!edibles

### ISSUE THREAD

**Issue by therealkaffie** [s4turns/PackBot#6]
This is a much needed feature for me to properly enjoy this discord bot. 

A user would trigger !edibles and then the bot would respond similar to the way that !beer does

**Comment by xDDFF** [comment]
added edibles 
![jpg](https://user-images.githubusercontent.com/40708795/62552706-f3c9d380-b822-11e9-80f8-c2e369120a3a.jpg)

###TODO: i will like some sort of input as in what is the command supposed to output. In case @therealkaffie wants something in particular.

**Comment by s4turns** [comment]
![image](https://user-images.githubusercontent.com/53133058/62580810-d02b7b00-b86c-11e9-9e4f-2e7093fdfc87.png)
